service: noname-app

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    OPENAI_MODEL: ${env:OPENAI_MODEL}
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_NAME: ${env:DB_NAME}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}

plugins:
  - serverless-plugin-typescript

functions:
  conversation:
    handler: src/handlers/conversation.handler.handler
    events:
      - http:
          path: /conversation
          method: post
          cors: true
